### ISSUE TITLE
SSL certificate expired when trying to connect naver api

### ISSUE THREAD

**Issue by developerlicw** [naver/searchad-apidoc#194]
We are using naver searchad api to download reports and update bidding prices everyday. And today, when we wanted to update our bidding price, the following error occurred:
` error: HTTPSConnectionPool(host='api.naver.com', port=443): Max retries exceeded with url: /ncc/keywords?fields=bidAmt (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))`

And we tried to curl naver api, got the following:
`$ curl https://api.naver.com
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
`

Besides, connecting to naver api directly using chrome browser also returns error, could you please check your SSL certificate and update it if necessary? Naver api is really very important to us.

Looking forward to you reply. Thanks very much.

**Comment by jayjay248** [comment]
We also have the same issue.

If you solve, please answer.

thanks.

**Comment by developerlicw** [comment]
@naver-searchad 
Sorry but could you please check this problem?

**Comment by developerlicw** [comment]
Seems to me that SSL certificate is recovered..
But still failing on requests. 
Will update if requests succeed.

**Comment by jayjay248** [comment]
we also ssl is resolved, but a request error occurs.

Is this an error message?  "unable to find valid certification path to requested target"

**Comment by developerlicw** [comment]
I think so, we have the same error as posted before. 
I heard that Korean is holiday today... Maybe we cannot get response today..

**Comment by jayjay248** [comment]
yes today is holiday. But Naver gave me an answer to my question. i think someone working today.

Let's wait a moment.

and this is naver's answer - (google's Translator)

2019년 3월 1일 오전 9시를 기준으로 만료된 인증서 일부가 제대로 교체되지 않아 서비스 이용이 불안정했습니다. 오후 3시13분을 기준으로 복구되어 현재 서비스 이용 가능합니다.
Service availability was unstable because part of the expired certificate was not replaced correctly at 9:00 am on March 1, 2019. It is restored at 3:13 p.m. and the service is available now.

서비스 이용에 불편을 드려서 죄송합니다.
We apologize for any inconvenience this may have caused you.

**Comment by developerlicw** [comment]
Thanks for the information.
I'm still getting the same error during request..
Waiting may be the only thing we can do now :(

**Comment by naver-searchad** [comment]
There was a problem with the replaced certificate chain and it has just been recovered. We apologize for the inconvenience in using the api

**Comment by developerlicw** [comment]
Tested just now and it's fixed! 
That's great! Thanks very much!
